### ISSUE TITLE
[BUG] Coverage report is failing

### ISSUE THREAD

**Issue by amgebauer** [4C-multiphysics/4C#155]
## Bug Description: What's going wrong?

I tested it in my pro-account and runners seem to have a little more storage.

@c-p-schmidt is currently testing in his repo how we need to adapt the chunking that it works also on non-pro runners.

## Possible Solution

 * [x] Adapt chunking
 * [ ] Other way to reduce storage

## Related Issues and Merge Requests

- Follows #128

**Comment by c-p-schmidt** [comment]
Adapting the number of chunks from 40 to 60 resolves this on my non-pro account fork. So it should also solve the problem here.
