### ISSUE TITLE
Add essential badges to README.md

### ISSUE THREAD

**Issue by sebproell** [4C-multiphysics/4C#42]
We should add badges that indicate the

- [x] status of Doxygen
- [x] status of readthedocs
- [x] convenience link to the website

and link to the respective page.

Further badges could be added for the state of different CI checks:

* [x] [![nightly_tests](https://github.com/4C-multiphysics/4C/actions/workflows/nightly_tests.yml/badge.svg)](https://github.com/4C-multiphysics/4C/actions/workflows/nightly_tests.yml)
* [x] [![checkcode](https://github.com/4C-multiphysics/4C/actions/workflows/checkcode.yml/badge.svg)](https://github.com/4C-multiphysics/4C/actions/workflows/checkcode.yml)

**Comment by amgebauer** [comment]
I added nightly_tests and checkcode to the description

**Comment by mayrmt** [comment]
@sebproell Maybe a link to the website? I often find it hard to find in many projects.

**Comment by mayrmt** [comment]
What about the coverage report? Or can't we do this while it's still on Gitlab?

**Comment by sebproell** [comment]
Since we create doxygen and rtd in the same workflow, I can only use one badge. I would say it should link to rtd and we prominently link to doxygen there?

FYI @ischeider

**Comment by ischeider** [comment]
> Since we create doxygen and rtd in the same workflow, I can only use one badge. I would say it should link to rtd and we prominently link to doxygen there?

From the PR I see that there are all the badges available, or do I misunderstood the main part?
Anyway, if the problem is elsewhere, we could have a section "Intended Audience" (or similar) on the landing page of rtd, where we state that this is the user documentation, and the developer documentation, Doxygen, can be found <here>. You mean something like this?

**Comment by sebproell** [comment]
Done. 

@ischeider Sorry for the confusion. We found a solution to have the badges.
